# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e2ed77c1184de5616ecf8302acc92ef04278424d6a2fa8a2b9cb7137e9d1fdfa605bbd9200da1a795fc8d58774c0c316227625e9c6be0eb49cafe129e1d14c22

test:
  secret_key_base: 000960223fb0861a6250fd6f5002127efc92d08260068b5fee94ad1dfee44035ca1f92cd8172840f58ab6a68777f93fb17286f39a1195c9518a02283ed021828

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
